version: "3.9"
services:

  oven_server:
    build: ./oven_server
    container_name: open_server_container
    ports:
      - "1935:1935"
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend_container
    depends_on:
      - oven_server
      - chat-backend

  chat-backend:
    build: ./chat-backend
    ports:
      - "9090:9090"
    container_name: chat-backend-container
